# Generated by Django 4.2.7 on 2025-11-27 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='cupos_max',
            field=models.PositiveIntegerField(default=32),
        ),
        migrations.AddField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='ABIERTO', max_length=20),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smashpointApp.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.IntegerField(default=1)),
                ('marcador_a', models.IntegerField(blank=True, null=True)),
                ('marcador_b', models.IntegerField(blank=True, null=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='smashpointApp.jugador')),
                ('jugador_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador_a', to='smashpointApp.jugador')),
                ('jugador_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador_b', to='smashpointApp.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smashpointApp.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('ESPERA', 'Lista de Espera'), ('CANCELADO', 'Cancelado')], default='INSCRITO', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smashpointApp.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smashpointApp.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'jugador')},
            },
        ),
    ]
