# Generated by Django 4.2.7 on 2025-11-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0002_torneo_cupos_max_torneo_estado_ranking_partido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='total_rondas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
