# Generated by Django 4.2.7 on 2025-11-27 04:00

from django.db import migrations, models
import smashpointApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0003_torneo_total_rondas'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT chileno válido (ej: 12.345.678-5)', max_length=12, null=True, unique=True, validators=[smashpointApp.models.validar_rut_chileno]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='licencia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
