# Generated by Django 4.2.7 on 2025-11-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0004_jugador_rut_alter_jugador_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='best_of',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad máxima de sets (3 ó 5). Se gana mayoría.'),
        ),
        migrations.AddField(
            model_name='partido',
            name='detalle_sets',
            field=models.CharField(blank=True, help_text='Formato: 11-7,8-11,11-9', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='etapa',
            field=models.CharField(choices=[('ELIMINACION', 'Eliminación'), ('GRUPOS', 'Grupos'), ('FINAL', 'Final')], default='ELIMINACION', max_length=15),
        ),
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.CharField(blank=True, help_text='Identificador del grupo (ej: A, B, C)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='sets_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='sets_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='numero_grupos',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de grupos (0 = sin fase de grupos)'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='smashpointApp.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'nombre')},
            },
        ),
    ]
