# Generated by Django 4.2.7 on 2025-11-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0005_partido_best_of_partido_detalle_sets_partido_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='jugadores',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='smashpointApp.jugador'),
        ),
    ]
