# Generated by Django 4.2.7 on 2025-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0006_grupo_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='origen',
            field=models.CharField(blank=True, help_text='Ciudad/Región de procedencia', max_length=80, null=True),
        ),
    ]
