# Generated by Django 4.2.16 on 2025-12-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0007_jugador_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='best_of',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad máxima de sets (3 ó 5). Se gana mayoría.'),
        ),
    ]
