# Generated by Django 4.2.7 on 2025-12-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashpointApp', '0010_update_torneo_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='categoria',
            field=models.CharField(choices=[('PENECA', 'Peneca'), ('PREINFANTIL', 'Preinfantil'), ('INFANTIL', 'Infantil'), ('JUVENIL', 'Juvenil'), ('TODO_COMPETIDOR', 'Todo Competidor'), ('PARALIMPICO', 'Paralímpico'), ('MASTER', 'Máster')], max_length=20),
        ),
    ]
